<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Information Form</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Segoe UI', Arial, sans-serif;
        }
        
        body {
            background-color: #f5f5f5;
            padding: 20px;
            color: #333;
        }
        
        .form-container {
            max-width: 800px;
            margin: 0 auto;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            padding: 30px;
        }
        
        .form-title {
            font-size: 22px;
            font-weight: 600;
            margin-bottom: 25px;
            color: #2c3e50;
            border-bottom: 2px solid #eaeaea;
            padding-bottom: 10px;
        }
        
        .form-section {
            margin-bottom: 25px;
        }
        
        .section-title {
            font-size: 18px;
            font-weight: 500;
            margin-bottom: 15px;
            color: #3498db;
            padding-bottom: 5px;
            border-bottom: 1px solid #eee;
        }
        
        .form-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
        }
        
        .form-group {
            display: flex;
            flex-direction: column;
        }
        
        .form-row {
            display: flex;
            gap: 10px;
            align-items: center;
        }
        
        .form-label {
            font-size: 14px;
            font-weight: 500;
            margin-bottom: 8px;
            color: #555;
        }
        
        .required::after {
            content: " *";
            color: #e74c3c;
        }
        
        .form-input, .form-select {
            padding: 10px 12px;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 14px;
            transition: border-color 0.3s;
        }
        
        .form-input:focus, .form-select:focus {
            outline: none;
            border-color: #3498db;
        }
        
        .date-inputs {
            display: flex;
            gap: 5px;
        }
        
        .date-input {
            width: 60px;
            text-align: center;
        }
        
        .radio-group {
            display: flex;
            gap: 15px;
            margin-top: 5px;
        }
        
        .radio-option {
            display: flex;
            align-items: center;
            gap: 5px;
        }
        
        .radio-option input {
            margin-right: 5px;
        }
        
        .full-width {
            grid-column: span 2;
        }
        
        .textarea-group {
            grid-column: span 2;
        }
        
        textarea {
            min-height: 80px;
            resize: vertical;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 14px;
            font-family: inherit;
        }
        
        .button-group {
            display: flex;
            justify-content: flex-end;
            gap: 15px;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
        }
        
        .btn {
            padding: 10px 24px;
            border: none;
            border-radius: 4px;
            font-size: 14px;
            font-weight: 500;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        
        .btn-register {
            background-color: #3498db;
            color: white;
        }
        
        .btn-register:hover {
            background-color: #2980b9;
        }
        
        .btn-cancel {
            background-color: #ecf0f1;
            color: #7f8c8d;
        }
        
        .btn-cancel:hover {
            background-color: #d5dbdb;
        }
        
        .autogenerated {
            background-color: #f8f9fa;
            color: #7f8c8d;
            font-style: italic;
        }
        
        .form-hint {
            font-size: 12px;
            color: #95a5a6;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <h1 class="form-title">Patient Information</h1>
        
        <div class="form-section">
            <div class="form-grid">
                <div class="form-group">
                    <label class="form-label">Patient ID</label>
                    <input type="text" class="form-input autogenerated" value="AUTOGENERATED" readonly>
                </div>
                
                <div class="form-group">
                    <label class="form-label required">Full Name</label>
                    <input type="text" class="form-input" placeholder="Full Name">
                </div>
                
                <div class="form-group">
                    <label class="form-label required">Date of Birth</label>
                    <div class="date-inputs">
                        <input type="text" class="form-input date-input" placeholder="D" maxlength="2">
                        <input type="text" class="form-input date-input" placeholder="M" maxlength="2">
                        <input type="text" class="form-input date-input" placeholder="Y" maxlength="4">
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="form-label required">Phone Number</label>
                    <input type="tel" class="form-input" placeholder="Phone Number">
                </div>
                
                <div class="form-group">
                    <label class="form-label">Email</label>
                    <input type="email" class="form-input" placeholder="Email">
                </div>
                
                <div class="form-group">
                    <label class="form-label required">Sex / Gender</label>
                    <select class="form-select">
                        <option value="" disabled selected>Select</option>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                        <option value="other">Other</option>
                        <option value="prefer-not-to-say">Prefer not to say</option>
                    </select>
                </div>
                
                <div class="form-group">
                    <label class="form-label">ZIP / Postal Code</label>
                    <input type="text" class="form-input" placeholder="ZIP / Postal Code">
                </div>
            </div>
        </div>
        
        <div class="form-section">
            <h2 class="section-title">Medical History</h2>
            <div class="form-grid">
                <div class="form-group">
                    <label class="form-label">Past Surgeries / Hospitalizations</label>
                    <textarea placeholder="Past Surgeries / Hospitalizations"></textarea>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Allergies</label>
                    <textarea placeholder="Allergies"></textarea>
                </div>
            </div>
        </div>
        
        <div class="form-section">
            <div class="form-grid">
                <div class="form-group">
                    <label class="form-label">Smoking Status</label>
                    <div class="radio-group">
                        <label class="radio-option">
                            <input type="radio" name="smoking" value="non-smoker">
                            Non-smoker
                        </label>
                        <label class="radio-option">
                            <input type="radio" name="smoking" value="former-smoker">
                            Former smoker
                        </label>
                        <label class="radio-option">
                            <input type="radio" name="smoking" value="current-smoker">
                            Current smoker
                        </label>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Alcohol Consumption</label>
                    <div class="radio-group">
                        <label class="radio-option">
                            <input type="radio" name="alcohol" value="none">
                            None
                        </label>
                        <label class="radio-option">
                            <input type="radio" name="alcohol" value="occasional">
                            Occasional
                        </label>
                        <label class="radio-option">
                            <input type="radio" name="alcohol" value="regular">
                            Regular
                        </label>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="form-section">
            <div class="form-grid">
                <div class="form-group">
                    <label class="form-label required">Assigned Doctor</label>
                    <select class="form-select">
                        <option value="" disabled selected>Select</option>
                        <option value="dr-johnson">Dr. Sarah Johnson</option>
                        <option value="dr-brown">Dr. Michael Brown</option>
                        <option value="dr-wilson">Dr. Emma Wilson</option>
                        <option value="dr-davis">Dr. Robert Davis</option>
                    </select>
                    <span class="form-hint">Select a doctor from the list</span>
                </div>
                
                <div class="form-group">
                    <label class="form-label required">Registration Date</label>
                    <input type="text" class="form-input" placeholder="dd/mm/yyyy">
                </div>
            </div>
        </div>
        
        <div class="form-section">
            <div class="form-grid">
                <div class="form-group textarea-group full-width">
                    <label class="form-label">Special Notes / Remarks</label>
                    <textarea placeholder="Special Notes / Remarks"></textarea>
                </div>
            </div>
        </div>
        
        <div class="button-group">
            <button class="btn btn-cancel">Cancel</button>
            <button class="btn btn-register">Register Patient</button>
        </div>
    </div>

    <script>
        // Add some basic interactivity
        document.querySelector('.btn-cancel').addEventListener('click', function() {
            if (confirm('Are you sure you want to cancel? All unsaved changes will be lost.')) {
                // Reset form
                document.querySelectorAll('input:not(.autogenerated), textarea, select').forEach(element => {
                    if (element.tagName === 'SELECT') {
                        element.selectedIndex = 0;
                    } else if (element.type === 'radio' || element.type === 'checkbox') {
                        element.checked = false;
                    } else {
                        element.value = '';
                    }
                });
            }
        });
        
        document.querySelector('.btn-register').addEventListener('click', function() {
            // Basic validation for required fields
            const requiredFields = document.querySelectorAll('.required');
            let isValid = true;
            
            requiredFields.forEach(label => {
                const input = label.parentElement.querySelector('input, select, textarea');
                if (input) {
                    if (!input.value.trim()) {
                        isValid = false;
                        input.style.borderColor = '#e74c3c';
                    } else {
                        input.style.borderColor = '#ddd';
                    }
                }
            });
            
            if (isValid) {
                alert('Patient registered successfully!');
                // In a real app, you would submit the form here
            } else {
                alert('Please fill in all required fields (marked with *).');
            }
        });
        
        // Clear error styling when user starts typing
        document.querySelectorAll('input, select, textarea').forEach(element => {
            element.addEventListener('input', function() {
                this.style.borderColor = '#ddd';
            });
        });
    </script>
</body>
</html>