@extends('layouts.app')

@section('title', 'Patients')

@section('content')
    <div class="app">
        <!-- SIDEBAR -->
        @include('layouts.sidebar')

        <!-- MAIN CONTENT -->
        <main class="flex-1 p-6">

            <!-- HEADER -->
            <div class="flex w-full sm:w-auto gap-2 mb-6">
                <h1 class="text-2xl font-semibold text-slate-700">Patient Lists</h1>
            </div>

            <!-- Top Actions -->
            <div class="flex justify-end items-center mb-6 gap-3">
                <div class="flex gap-2">
                    <input type="text" placeholder="Search by name..." class="border rounded px-3 py-2 w-64">
                </div>

                <!-- + Add Patient Button -->
                <button type="button" class="add-patient-btn" onclick="openAddModal()">
                    + Add Patient
                </button>
            </div>

            <!-- PATIENT TABLE -->
            <div class="bg-white rounded-xl shadow overflow-x-auto">
                <table class="w-full text-sm">
                    <thead class="bg-sky-50 text-slate-600">
                        <tr>
                            <th class="px-4 py-3 text-left">ID</th>
                            <th class="px-4 py-3 text-left">Name</th>
                            <th class="px-4 py-3 text-left">Age</th>
                            <th class="px-4 py-3 text-left">Phone</th>
                            <th class="px-4 py-3 text-left">Assigned Doctor</th>
                            <th class="px-4 py-3 text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y">
                        @forelse ($patients as $p)
                            <tr class="hover:bg-slate-50">
                                <td class="px-4 py-3">{{ $p->id }}</td>
                                <td class="px-4 py-3">{{ $p->name }}</td>
                                <td class="px-4 py-3">{{ $p->age }}</td>
                                <td class="px-4 py-3">{{ $p->phone }}</td>
                                <td class="px-4 py-3">{{ $p->doctor }}</td>
                                <td class="px-4 py-3 text-center space-x-2">
                                    <button class="text-amber-600 hover:underline" onclick="openViewModal()">View</button>
                                    <button class="text-red-600 hover:underline">Delete</button>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6" class="px-4 py-3 text-center text-gray-500">No patients found.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

        </main>
    </div>

    <!-- VIEW PATIENT MODAL -->
    <div id="viewModal" class="fixed inset-0 bg-black/40 hidden items-center justify-center z-50">
        <div class="bg-white rounded-xl w-full max-w-lg p-6">
            <h2 class="text-xl font-semibold mb-4 text-slate-700">Patient Details</h2>
            <div class="grid grid-cols-2 gap-4 text-sm">
                <div><b>ID:</b> P001</div>
                <div><b>Age:</b> 29</div>
                <div><b>Name:</b> Aung Min</div>
                <div><b>Phone:</b> 09-12345678</div>
                <div class="col-span-2"><b>Assigned Doctor:</b> Dr. Kyaw</div>
                <div class="col-span-2"><b>Notes:</b> No allergies reported.</div>
            </div>
            <div class="text-right mt-6">
                <button onclick="closeViewModal()" class="px-4 py-2 bg-slate-200 rounded hover:bg-slate-300">Close</button>
            </div>
        </div>
    </div>

    <!-- ADD PATIENT MODAL -->
    <div id="addModal" class="fixed inset-0 bg-black/40 hidden items-center justify-center z-50 overflow-auto py-10">
        <div class="patient-form-container">
            <h1 class="form-title">Patient Registration</h1>

            <form method="POST" action="{{ route('patients.store') }}" id="patientForm">
                @csrf

                <!-- Patient Information Section -->
                <h2 class="section-title">Patient Information</h2>
                <div class="form-row">
                    <div class="form-group">
                        <label>Patient ID</label>
                        <div class="patient-id">AUTOGENERATED</div>
                    </div>
                    <div class="form-group">
                        <label class="required">Full Name</label>
                        <input type="text" name="full_name" placeholder="Enter Full Name" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group">
                        <label class="required">National ID / Passport</label>
                        <input type="text" name="national_id_passport" placeholder="Enter National ID or Passport Number"
                            required>
                    </div>
                    <div class="form-group">
                        <label class="required">Age</label>
                        <input type="number" name="age" placeholder="Enter Age" min="0" max="120" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group">
                        <label class="required">Date of Birth</label>
                        <div class="dob-inputs">
                            <input type="number" name="date_of_birth_day" placeholder="D" min="1" max="31"
                                required>
                            <input type="number" name="date_of_birth_month" placeholder="M" min="1" max="12"
                                required>
                            <input type="number" name="date_of_birth_year" placeholder="Y" min="1900" max="2026"
                                required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="required">Sex / Gender</label>
                        <select name="sex_gender" required>
                            <option value="" disabled selected>Select</option>
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                            <option value="other">Other</option>
                            <option value="prefer_not_to_say">Prefer not to say</option>
                        </select>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group">
                        <label class="required">Phone Number</label>
                        <input type="tel" name="phone_number" placeholder="Enter Phone Number" required>
                    </div>
                    <div class="form-group">
                        <label class="required">Address</label>
                        <input type="text" name="address" placeholder="Enter Address" required>
                    </div>
                </div>

                <!-- Medical History Section -->
                <h2 class="section-title">Medical History</h2>
                <div class="form-row">
                    <div class="form-group">
                        <label>Known Medical Conditions</label>
                        <textarea name="known_medical_conditions" rows="2" placeholder="List known medical conditions"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Allergies</label>
                        <textarea name="allergies" rows="2" placeholder="List any allergies"></textarea>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group">
                        <label>Blood Type</label>
                        <select name="blood_type">
                            <option value="" selected>Select</option>
                            <option value="A+">A+</option>
                            <option value="A-">A-</option>
                            <option value="B+">B+</option>
                            <option value="B-">B-</option>
                            <option value="O+">O+</option>
                            <option value="O-">O-</option>
                            <option value="AB+">AB+</option>
                            <option value="AB-">AB-</option>
                            <option value="unknown">Unknown</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Alcohol Consumption</label>
                        <div class="radio-group">
                            <label><input type="radio" name="alcohol_consumption" value="none" checked> None</label>
                            <label><input type="radio" name="alcohol_consumption" value="occasional">
                                Occasional</label>
                            <label><input type="radio" name="alcohol_consumption" value="regular"> Regular</label>
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group">
                        <label class="required">Assigned Doctor</label>
                        <select name="assigned_doctor" required>
                            <option value="" disabled selected>Select Doctor</option>
                            @foreach ($doctors as $doctor)
                                <option value="{{ $doctor->id }}">{{ $doctor->full_name }} ({{ $doctor->speciality }})
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="required">Registration Date</label>
                        <input type="date" name="registration_date" required>
                    </div>
                </div>

                <div class="button-container">
                    <button type="button" onclick="closeAddModal()" class="cancel-btn">Cancel</button>
                    <button type="submit" class="register-btn">Register Patient</button>
                </div>
            </form>
        </div>
    </div>

    <!-- STYLES -->
    <style>
        /* === BUTTON === */
        .add-patient-btn {
            padding: 10px 20px;
            border-radius: 11px;
            font-weight: 600;
            font-size: 15px;
            background: linear-gradient(to right, #3b82f6, #2563eb);
            color: white;
            border: none;
            cursor: pointer;
            transition: all 0.3s;
        }

        .add-patient-btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(37, 99, 235, 0.3);
        }

        /* === MODAL & FORM === */
        .patient-form-container {
            background-color: #f6fcff;
            width: 800px;
            max-width: 95%;
            padding: 30px 35px;
            border-radius: 14px;
            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.08);
        }

        .form-title {
            text-align: center;
            color: #2b6de8;
            font-size: 28px;
            margin-bottom: 30px;
            font-weight: 600;
        }

        .section-title {
            color: #1f3b57;
            font-size: 20px;
            margin: 25px 0 15px 0;
            padding-bottom: 8px;
            border-bottom: 2px solid #e0f0ff;
            font-weight: 600;
        }

        .form-row {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            margin-bottom: 18px;
        }

        .form-group {
            flex: 1;
            min-width: 250px;
        }

        .form-group label {
            display: block;
            font-weight: 600;
            color: #1f3b57;
            margin-bottom: 6px;
        }

        .form-group input,
        .form-group select,
        .form-group textarea {
            width: 100%;
            padding: 12px 14px;
            border-radius: 10px;
            border: 2px solid #c8e1f3;
            font-size: 15px;
            background-color: #fff;
        }

        .form-group input:focus,
        .form-group select:focus,
        .form-group textarea:focus {
            border-color: #4a90e2;
            box-shadow: 0 0 0 3px rgba(74, 144, 226, 0.2);
        }

        .patient-id {
            padding: 12px 14px;
            border-radius: 10px;
            border: 2px solid #c8e1f3;
            background-color: #eaf4fb;
            font-weight: 600;
            color: #355f8c;
            min-height: 46px;
        }

        .radio-group {
            display: flex;
            gap: 20px;
            margin-top: 5px;
        }

        .radio-group label {
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .button-container {
            display: flex;
            gap: 15px;
            margin-top: 30px;
        }

        .register-btn {
            flex: 1;
            padding: 14px;
            border: none;
            border-radius: 12px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            background: linear-gradient(to right, #3b82f6, #2563eb);
            color: #fff;
            transition: all 0.3s;
        }

        .register-btn:hover {
            background: linear-gradient(to right, #2563eb, #1d4ed8);
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(37, 99, 235, 0.3);
        }

        .cancel-btn {
            flex: 1;
            padding: 14px;
            border: none;
            border-radius: 12px;
            font-size: 16px;
            font-weight: 600;
            background-color: #f1f5f9;
            color: #64748b;
            border: 2px solid #cbd5e1;
        }

        .cancel-btn:hover {
            background-color: #e2e8f0;
            transform: translateY(-2px);
        }

        .dob-inputs {
            display: flex;
            gap: 10px;
        }

        .dob-inputs input {
            flex: 1;
            text-align: center;
        }
    </style>

    <!-- SCRIPTS -->
    <script>
        function openViewModal() {
            document.getElementById('viewModal').classList.remove('hidden');
            document.getElementById('viewModal').classList.add('flex');
        }

        function closeViewModal() {
            document.getElementById('viewModal').classList.add('hidden');
        }

        function openAddModal() {
            document.getElementById('addModal').classList.remove('hidden');
            document.getElementById('addModal').classList.add('flex');
        }

        function closeAddModal() {
            document.getElementById('addModal').classList.add('hidden');
        }
    </script>

@endsection
